index:
    path: /
    controller: App\Controller\AppController::renderApp

get_user_boxes:
    path: /get_user_boxes
    controller: App\Controller\PageInfoController::getUserBoxes

get_signature:
    path: /get_signature
    controller: App\Controller\PageInfoController::getSignature