index:
    path: /
    controller: App\Controller\AppController::renderApp

get_user_boxes:
    path: /get_user_boxes
    controller: App\Controller\PageInfoController::getUserBoxes

get_templates:
    path: /get_templates
    controller: App\Controller\PageInfoController::getTemplates

get_signature:
    path: /get_signature
    controller: App\Controller\PageInfoController::getSignature

get_template_structure:
    path: /get_template_structure
    controller: App\Controller\PageInfoController::getTemplateStructure